const Data = [
  {
    uri: require('../../photo/image/download.jpeg'),
    name: 'Jany',
    FullName: 'Janybiber',
    button: 'Follow',
    touch: 'x',
  },
  {
    uri: require('../../photo/image/AA.jpeg'),
    name: 'Ani_Alek',
    FullName: 'Annabella',
    button: 'Follow',
    touch: 'x',
  },
  {
    uri: require('../../photo/image/BB.jpeg'),
    name: 'Jagii_lebron',
    FullName: 'James',
    button: 'Follow',
    touch: 'x',
  },
  {
    uri: require('../../photo/image/download.jpeg'),
    name: 'Jany',
    FullName: 'Janybiber',
    button: 'Follow',
    touch: 'x',
  },
  {
    uri: require('../../photo/image/AA.jpeg'),
    name: 'Ani_Alek',
    FullName: 'Annabella',
    button: 'Follow',
    touch: 'x',
  },
  {
    uri: require('../../photo/image/BB.jpeg'),
    name: 'Jagii_lebron',
    FullName: 'James',
    button: 'Follow',
    touch: 'x',
  },
  {
    uri: require('../../photo/image/download.jpeg'),
    name: 'Jany',
    FullName: 'Janybiber',
    button: 'Follow',
    touch: 'x',
  },
  {
    uri: require('../../photo/image/AA.jpeg'),
    name: 'Ani_Alek',
    FullName: 'Annabella',
    button: 'Follow',
    touch: 'x',
  },
  {
    uri: require('../../photo/image/BB.jpeg'),
    name: 'Jagii_lebron',
    FullName: 'James',
    button: 'Follow',
    touch: 'x',
  },
  {
    uri: require('../../photo/image/download.jpeg'),
    name: 'Jany',
    FullName: 'Janybiber',
    button: 'Follow',
    touch: 'x',
  },
  {
    uri: require('../../photo/image/AA.jpeg'),
    name: 'Ani_Alek',
    FullName: 'Annabella',
    button: 'Follow',
    touch: 'x',
  },
  {
    uri: require('../../photo/image/BB.jpeg'),
    name: 'Jagii_lebron',
    FullName: 'James',
    button: 'Follow',
    touch: 'x',
  },
];
export default Data;
